name: Release Version

on:
    release:
        types:
            - published

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                  go-version: "^1.16"
            - name: Build binaries
              run: make build-platforms
            - name: Compress binaries
              run: for f in ./acert-*; do tar -zcf "${f}.tar.gz" "${f}" && zip "${f}.zip" "${f}"; done
            - name: Upload binaries
              uses: actions/github-script@v3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const fs = require("fs").promises;

                      // Get context
                      const { repo: { owner, repo } } = context;
                      const release = await github.repos.getReleaseByTag({
                          owner,
                          repo,
                          tag: process.env.GITHUB_REF.replace("refs/tags/", ""),
                      });

                      // Get files to upload
                      const files = await fs
                          .readdir(".")
                          .then((files) =>
                              files.filter(
                                  (name) => name.match(/\.tar\.gz$/) || name.match(/\.zip$/)
                              )
                          );

                      // Upload files
                      console.log("Uploading binaries...");
                      await Promise.all(
                          files.map(async (name) =>
                              github.repos.uploadReleaseAsset({
                                  owner,
                                  repo,
                                  release_id: release.data.id,
                                  name,
                                  data: await fs.readFile(name),
                              })
                          )
                      );
                      console.log("All files uploaded successfully.");
